import numpy as np
import tensorflow as tf

# Load test data
X_test = np.loadtxt('UCI HAR Dataset/test/X_test.txt')
y_test = np.loadtxt('UCI HAR Dataset/test/y_test.txt', dtype=int) - 1

# Load quantized model to get input quantization parameters
interpreter = tf.lite.Interpreter(model_path='model_int8.tflite')
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
input_scale, input_zero_point = input_details[0]['quantization']

# Pick 10 samples — 1-2 per class for variety
# Classes: 0=Walking, 1=WalkingUp, 2=WalkingDown, 3=Sitting, 4=Standing, 5=Laying
selected_indices = []
for class_id in range(6):
    indices = np.where(y_test == class_id)[0][:2]
    selected_indices.extend(indices.tolist())

selected_indices = selected_indices[:12]  # 12 samples total, 2 per class

samples = X_test[selected_indices]
labels  = y_test[selected_indices]

# Quantize to INT8
samples_int8 = (samples / input_scale + input_zero_point).astype(np.int8)

# Class names for comments
class_names = ['Walking', 'WalkingUpstairs', 'WalkingDownstairs',
               'Sitting', 'Standing', 'Laying']

# Generate C header file
lines = []
lines.append('/* Auto-generated by generate_test_samples.py */')
lines.append('/* 12 UCI HAR test samples, quantized to INT8 */')
lines.append('')
lines.append('#ifndef TEST_SAMPLES_H')
lines.append('#define TEST_SAMPLES_H')
lines.append('')
lines.append('#include <stdint.h>')
lines.append('')
lines.append('#define NUM_TEST_SAMPLES  12')
lines.append('#define SAMPLE_SIZE       561')
lines.append('')
lines.append('static const char* class_names[6] = {')
lines.append('    "Walking", "WalkingUpstairs", "WalkingDownstairs",')
lines.append('    "Sitting", "Standing", "Laying"')
lines.append('};')
lines.append('')
lines.append('static const int8_t test_labels[NUM_TEST_SAMPLES] = {')
label_str = ', '.join([str(int(l)) for l in labels])
lines.append(f'    {label_str}')
lines.append('};')
lines.append('')
lines.append('static const int8_t test_samples[NUM_TEST_SAMPLES][SAMPLE_SIZE] = {')
for i, (sample, label) in enumerate(zip(samples_int8, labels)):
    lines.append(f'    /* Sample {i}: {class_names[int(label)]} */')
    values = ', '.join([str(int(v)) for v in sample])
    lines.append(f'    {{{values}}},')
lines.append('};')
lines.append('')
lines.append('#endif /* TEST_SAMPLES_H */')

output = '\n'.join(lines)
with open('test_samples.h', 'w') as f:
    f.write(output)

print(f"Generated test_samples.h")
print(f"Samples per class:")
for i in range(6):
    count = np.sum(labels == i)
    print(f"  {class_names[i]}: {count}")
print(f"Input scale: {input_scale:.6f}, zero_point: {input_zero_point}")